import { useState, useRef, useEffect } from "react";
import {
  buildBoxedCornerModel,
  fmtIn as bcFmtIn, fmtDec as bcFmtDec, ptsToPath as bcPtsToPath,
} from "../boxed-corner-core.js";
import { isMetric, fmtCm } from "../utils/formatting.js";
import { DEFAULT_SA } from "../utils/constants.js";
import {
  CP_TILE_W, CP_TILE_H,
  cpTilePlan, cpTileLabel, cpRowLabel, cpTestSquareSVG, cpRegistrationMarks,
} from "../utils/print-utils.js";
import TrustBadge from "../components/TrustBadge.jsx";
import PrintButton from "../components/PrintButton.jsx";
import FracInput from "../components/FracInput.jsx";

// ══════════════════════════════════════════════════════════════════════════════
// ── BOXED CORNER — finished-size calculator ──────────────────────────────────
// Geometry core lives in ./boxed-corner-core.js. This section is UI + print.
// ══════════════════════════════════════════════════════════════════════════════

const BC = {
  pumpkin:"#a84f14", pumpkinDark:"#763407", amber:"#ca6b27",
  cream:"#fffaf6", soft:"#f6e3d4", line:"#e6b88f", ink:"#4d2a15",
  muted:"#9a6b4e", green:"#1d6b45", stabilizer:"#3f7d6d", center:"#6c4f8c",
  warnBg:"#fff4df", warnLine:"#e6bf73", warnInk:"#7b4d08",
};
const BC_THEME={
  sec:BC.soft,hdr:BC.pumpkin,hdrTxt:"#fff",card:BC.cream,border:BC.line,
  label:BC.pumpkinDark,sub:BC.muted,accent:BC.pumpkin,inputBg:"#fbf1e9",inputTxt:BC.ink,
  resBg:"#efcdb3",resAccent:BC.pumpkinDark,resTxt:BC.ink,btnOn:BC.pumpkin,btnOnTxt:"#fff",
  btnOff:"#efd5bf",btnOffTxt:BC.pumpkinDark,info:BC.soft,infoBdr:BC.line,infoTxt:BC.ink,
  ok:"#e0f5ea",okBdr:"#5aaa80",okTxt:"#1a5c38",warn:BC.warnBg,warnBdr:BC.warnLine,warnTxt:BC.warnInk,
  nudgeBg:"#efd5bf",nudgeTxt:BC.pumpkinDark,pageBg:"#faf0e8",
};
function bcFmt(v){ return isMetric()?fmtCm(v):bcFmtIn(v); }
function bcFmtD(v){ return isMetric()?fmtCm(v):bcFmtDec(v); }

function BcSeg({options,value,set}){return <div className="bc-seg">{options.map(o=><button key={o.id} className={value===o.id?"on":""} onClick={()=>set(o.id)}>{o.label}</button>)}</div>;}

function bcRightAngleSVG(marker,X,Y,scale){
  const q=7,at={x:X(marker.at.x),y:Y(marker.at.y)};
  const e={x:marker.edgeDir.x*q,y:marker.edgeDir.y*q},c={x:marker.cutDir.x*q,y:marker.cutDir.y*q};
  return `<path d="M ${(at.x+e.x).toFixed(1)} ${(at.y+e.y).toFixed(1)} L ${(at.x+e.x+c.x).toFixed(1)} ${(at.y+e.y+c.y).toFixed(1)} L ${(at.x+c.x).toFixed(1)} ${(at.y+c.y).toFixed(1)}" fill="none" stroke="${BC.amber}" stroke-width="1.4"/>`;
}
function bcPanelDiagramSVG(m){
  const VW=760,VH=520,PAD=38,bb=m.cutBB,sc=Math.min((VW-PAD*2)/Math.max(bb.w,.001),(VH-PAD*2)/Math.max(bb.h,.001));
  const ox=(VW-bb.w*sc)/2-bb.minX*sc,oy=(VH-bb.h*sc)/2-bb.minY*sc,X=v=>v*sc+ox,Y=v=>v*sc+oy,map=pts=>pts.map(p=>({x:X(p.x),y:Y(p.y)}));
  let s=`<path d="${bcPtsToPath(map(m.cutPts),true)}" fill="#f7dfcd" fill-opacity=".52" stroke="none"/>`;
  for(const rp of m.removedPolys||[]) s+=`<path d="${bcPtsToPath(map(rp.pts),true)}" fill="#f6e3d4" fill-opacity=".72" stroke="#d69a6b" stroke-width="1.3" stroke-dasharray="5 4"/>`;
  if(m.stabilizer?.enabled&&m.stabilizer.valid&&m.stabilizer.pts?.length)s+=`<path d="${bcPtsToPath(map(m.stabilizer.pts),true)}" fill="none" stroke="${BC.stabilizer}" stroke-width="2.2" stroke-dasharray="12 5 2 5"/>`;
  for(const line of m.stitchLines||[])s+=`<path d="${bcPtsToPath(map(line.pts),false)}" fill="none" stroke="#858585" stroke-width="2" stroke-dasharray="9 7" stroke-linecap="round"/>`;
  if(m.centerLine){
    s+=`<line x1="${X(m.centerLine.a.x)}" y1="${Y(m.centerLine.a.y)}" x2="${X(m.centerLine.b.x)}" y2="${Y(m.centerLine.b.y)}" stroke="${BC.center}" stroke-width="2" stroke-dasharray="15 6 3 6"/>`;
    const cy=(Y(m.centerLine.a.y)+Y(m.centerLine.b.y))/2;
    s+=`<text x="${X(0)+10}" y="${cy}" transform="rotate(-90 ${X(0)+10} ${cy})" text-anchor="middle" font-family="Nunito,sans-serif" font-size="12" font-weight="900" fill="${BC.center}">CENTER / PLACE ON FOLD</text>`;
  }
  if(m.foldLine){s+=`<line x1="${X(m.foldLine.a.x)}" y1="${Y(m.foldLine.y)}" x2="${X(m.foldLine.b.x)}" y2="${Y(m.foldLine.y)}" stroke="#00a9b8" stroke-width="2.3" stroke-dasharray="10 6"/>`;s+=`<text x="${X((m.foldLine.a.x+m.foldLine.b.x)/2)}" y="${Y(m.foldLine.y)-8}" text-anchor="middle" font-family="Nunito,sans-serif" font-size="13" font-weight="900" fill="#007783">BOTTOM FOLD</text>`;}
  s+=`<path d="${bcPtsToPath(map(m.cutPts),true)}" fill="none" stroke="${BC.pumpkin}" stroke-width="3.4" stroke-linejoin="round"/>`;
  for(const r of m.rightAngles||[])s+=bcRightAngleSVG(r,X,Y,sc);
  const c=m.construction.bottomCorner.left,mid1={x:(c.sideFoot.x+c.meet.x)/2,y:(c.sideFoot.y+c.meet.y)/2},mid2={x:(c.meet.x+c.edgeFoot.x)/2,y:(c.meet.y+c.edgeFoot.y)/2};
  s+=`<text x="${X(mid1.x)-8}" y="${Y(mid1.y)-7}" text-anchor="end" font-family="DM Mono,monospace" font-size="12" font-weight="500" fill="${BC.pumpkinDark}">${bcFmt(m.construction.bottomCorner.sideLegCut)}</text>`;
  s+=`<text x="${X(mid2.x)+9}" y="${Y(mid2.y)}" text-anchor="start" font-family="DM Mono,monospace" font-size="12" font-weight="500" fill="${BC.pumpkinDark}">${bcFmt(m.construction.bottomCorner.edgeLegCut)}</text>`;
  s+=`<text x="${VW/2}" y="${VH-8}" text-anchor="middle" font-family="Nunito,sans-serif" font-size="13" font-weight="800" fill="${BC.muted}">Cut envelope ${bcFmt(m.cutBB.w)} W × ${bcFmt(m.cutBB.h)} H · ${m.labels.layout}</text>`;
  return s;
}

function bcPrintDoc(title,geom,spanW,spanH,rows,legend){
  const plan=cpTilePlan(spanW,spanH,true);let draw=geom;if(plan.rotated)draw=`<g transform="translate(${spanH.toFixed(4)} 0) rotate(90)">${geom}</g>`;let tiles="";
  for(let r=0;r<plan.rows;r++)for(let c=0;c<plan.cols;c++){
    const vx=c*CP_TILE_W,vy=r*CP_TILE_H,label=cpRowLabel(r)+(c+1),last=r===plan.rows-1&&c===plan.cols-1;let inner=draw;
    inner+=`<rect x="${vx}" y="${vy}" width="${CP_TILE_W}" height="${CP_TILE_H}" fill="none" stroke="#000" stroke-width="0.025"/>`+cpRegistrationMarks(vx,vy,CP_TILE_W,CP_TILE_H);
    const L=c>0?cpRowLabel(r)+c:null,R=c<plan.cols-1?cpRowLabel(r)+(c+2):null,U=r>0?cpRowLabel(r-1)+(c+1):null,D=r<plan.rows-1?cpRowLabel(r+1)+(c+1):null;
    if(L)inner+=`<text x="${vx+.08}" y="${vy+CP_TILE_H/2}" font-size=".12" font-weight="700" font-family="Nunito,sans-serif" fill="#777">← ${L}</text>`;if(R)inner+=`<text x="${vx+CP_TILE_W-.08}" y="${vy+CP_TILE_H/2}" font-size=".12" font-weight="700" font-family="Nunito,sans-serif" fill="#777" text-anchor="end">${R} →</text>`;if(U)inner+=`<text x="${vx+CP_TILE_W/2}" y="${vy+.15}" font-size=".12" font-weight="700" font-family="Nunito,sans-serif" fill="#777" text-anchor="middle">↑ ${U}</text>`;if(D)inner+=`<text x="${vx+CP_TILE_W/2}" y="${vy+CP_TILE_H-.08}" font-size=".12" font-weight="700" font-family="Nunito,sans-serif" fill="#777" text-anchor="middle">↓ ${D}</text>`;
    tiles+=`<div class="tile${last?" last":""}"><div class="tlabel">${title} — ${label}</div><svg width="${CP_TILE_W}in" height="${CP_TILE_H}in" viewBox="${vx} ${vy} ${CP_TILE_W} ${CP_TILE_H}" xmlns="http://www.w3.org/2000/svg">${inner}</svg></div>`;
  }
  const details=rows.map(x=>`<tr><td>${x[0]}</td><td>${x[1]}</td></tr>`).join(""),w=window.open("","_blank");if(!w){window.alert("The print window was blocked. Allow pop-ups, then try again.");return;}
  w.document.write(`<!DOCTYPE html><html><head><title>${title}</title><style>@page{margin:.5in}body{font-family:Nunito,system-ui,sans-serif;margin:0;color:#222}.page,.tile{page-break-after:always}.tile.last{page-break-after:auto}.tlabel{padding:3pt 0 0;font-size:7pt;font-weight:700;text-align:center}.tile svg{display:block;margin:0 auto}h1{font-size:15pt;margin:0 0 3pt;color:${BC.pumpkin}}h2{font-size:10pt;margin:0 0 8pt;color:#555}table{border-collapse:collapse;width:100%;font-size:10pt}td{border:1px solid #ddd;padding:4pt 7pt}td:first-child{font-weight:700;width:38%}.note{font-size:11pt;font-weight:800;margin-top:9pt;line-height:1.5}.legend{font-size:7.5pt;color:#444;margin-top:5pt}</style></head><body><div class="page"><h1>${title}</h1><h2>MoonShot Bag Calculator · ${plan.pages} pattern page${plan.pages===1?"":"s"} · ${plan.rows} × ${plan.cols} · 7″ × 9.68″ printable tiles${plan.rotated?" · auto-rotated":""}</h2><p style="font-size:9pt;font-weight:700;color:#555;margin:0 0 2pt">Verify both test squares before cutting fabric:</p>${cpTestSquareSVG()}<table>${details}</table><p class="legend">${legend}</p><p class="note">Print at 100% or Actual Size. Turn off Fit to Page, scaling, and browser headers/footers. Verify both test squares. Assemble matching tile edges using page labels and registration crosses.</p></div>${tiles}</body></html>`);w.document.close();const fire=()=>{const ready=w.document.fonts?.ready||Promise.resolve();ready.then(()=>setTimeout(()=>w.print(),80));};if(w.document.readyState==="complete")fire();else w.addEventListener("load",fire,{once:true});
}
function bcPrintPanel(m,includeStabilizer=false){
  if(!m.valid)return;const P=.4,ox=m.cutBB.minX-P,oy=m.cutBB.minY-P,shift=pts=>pts.map(q=>({x:q.x-ox,y:q.y-oy}));let g="";
  for(const line of m.stitchLines||[])g+=`<path d="${bcPtsToPath(shift(line.pts),false)}" fill="none" stroke="#888" stroke-width=".022" stroke-dasharray=".15 .10" stroke-linecap="round"/>`;
  if(includeStabilizer&&m.stabilizer?.valid)g+=`<path d="${bcPtsToPath(shift(m.stabilizer.pts),true)}" fill="none" stroke="${BC.stabilizer}" stroke-width=".028" stroke-dasharray=".22 .09 .04 .09"/>`;
  if(m.centerLine){const a={x:m.centerLine.a.x-ox,y:m.centerLine.a.y-oy},b={x:m.centerLine.b.x-ox,y:m.centerLine.b.y-oy},mx=(a.x+b.x)/2,my=(a.y+b.y)/2;g+=`<line x1="${a.x.toFixed(4)}" y1="${a.y.toFixed(4)}" x2="${b.x.toFixed(4)}" y2="${b.y.toFixed(4)}" stroke="${BC.center}" stroke-width=".024" stroke-dasharray=".28 .12 .05 .12"/>`;g+=`<text x="${(mx+.12).toFixed(4)}" y="${my.toFixed(4)}" transform="rotate(-90 ${(mx+.12).toFixed(4)} ${my.toFixed(4)})" font-size=".12" font-weight="800" font-family="Nunito,sans-serif" fill="${BC.center}" text-anchor="middle">CENTER / PLACE ON FOLD</text>`;}
  if(m.foldLine)g+=`<line x1="${(m.foldLine.a.x-ox).toFixed(4)}" y1="${(m.foldLine.y-oy).toFixed(4)}" x2="${(m.foldLine.b.x-ox).toFixed(4)}" y2="${(m.foldLine.y-oy).toFixed(4)}" stroke="#00a9b8" stroke-width=".024" stroke-dasharray=".2 .12"/>`;
  g+=`<path d="${bcPtsToPath(shift(m.cutPts),true)}" fill="none" stroke="${BC.pumpkin}" stroke-width=".04" stroke-linejoin="round"/>`;
  for(const r of m.rightAngles){const at={x:r.at.x-ox,y:r.at.y-oy},q=.10,e={x:r.edgeDir.x*q,y:r.edgeDir.y*q},c={x:r.cutDir.x*q,y:r.cutDir.y*q};g+=`<path d="M ${(at.x+e.x).toFixed(4)} ${(at.y+e.y).toFixed(4)} L ${(at.x+e.x+c.x).toFixed(4)} ${(at.y+e.y+c.y).toFixed(4)} L ${(at.x+c.x).toFixed(4)} ${(at.y+c.y).toFixed(4)}" fill="none" stroke="${BC.pumpkin}" stroke-width=".016"/>`;}
  const c=m.construction.bottomCorner,rows=[["Finished size",`${bcFmt(m.checks.topW)} top · ${bcFmt(m.checks.botW)} bottom · ${bcFmt(m.checks.height)} H · ${bcFmt(m.checks.depth)} D`],["Panel cut envelope",`${bcFmt(m.cutBB.w)} W × ${bcFmt(m.cutBB.h)} H`],["Cut quantity",`${m.quantity} · ${m.labels.layout}`],["Bottom corner — from side",bcFmt(c.sideLegCut)],[m.params.layout==="fold"?"Bottom corner — from fold":"Bottom corner — from bottom edge",bcFmt(c.edgeLegCut)],["Usable matched legs after side/bottom seam",`${bcFmt(c.sideLegFinished)} + ${bcFmt(c.edgeLegFinished)}`],["Seam allowance",bcFmt(m.params.sa)],["Construction",`${m.labels.shape} · ${m.labels.topMode}`]];
  if(includeStabilizer&&m.stabilizer?.valid)rows.push(["Stabilizer overlay",`${bcFmt(m.stabilizer.offset)} inside fabric cut edge`]);
  const stabLegend=includeStabilizer&&m.stabilizer?.valid?` · green dash-dot = stabilizer cut line`:"";
  bcPrintDoc("Boxed Corner — Main Panel",g,m.cutBB.w+P*2,m.cutBB.h+P*2,rows,`Pumpkin solid = fabric cut · grey dashed = assembly stitch lines only · purple dash-dot = center / place on fold · cyan dashed = bottom fold${stabLegend}. Small corner symbols confirm that each box-cut leg leaves its source edge at 90°.`);
}
function bcPrintStabilizer(m){
  if(!m.valid||!m.stabilizer?.enabled||!m.stabilizer.valid)return;const P=.4,bb=m.stabilizer.bb,ox=bb.minX-P,oy=bb.minY-P,shift=pts=>pts.map(q=>({x:q.x-ox,y:q.y-oy}));let g="";
  if(m.stabilizer.centerLine){const a={x:m.stabilizer.centerLine.a.x-ox,y:m.stabilizer.centerLine.a.y-oy},b={x:m.stabilizer.centerLine.b.x-ox,y:m.stabilizer.centerLine.b.y-oy},mx=(a.x+b.x)/2,my=(a.y+b.y)/2;g+=`<line x1="${a.x.toFixed(4)}" y1="${a.y.toFixed(4)}" x2="${b.x.toFixed(4)}" y2="${b.y.toFixed(4)}" stroke="${BC.center}" stroke-width=".024" stroke-dasharray=".28 .12 .05 .12"/>`;g+=`<text x="${(mx+.12).toFixed(4)}" y="${my.toFixed(4)}" transform="rotate(-90 ${(mx+.12).toFixed(4)} ${my.toFixed(4)})" font-size=".12" font-weight="800" font-family="Nunito,sans-serif" fill="${BC.center}" text-anchor="middle">CENTER / PLACE ON FOLD</text>`;}
  if(m.stabilizer.foldLine)g+=`<line x1="${(m.stabilizer.foldLine.a.x-ox).toFixed(4)}" y1="${(m.stabilizer.foldLine.a.y-oy).toFixed(4)}" x2="${(m.stabilizer.foldLine.b.x-ox).toFixed(4)}" y2="${(m.stabilizer.foldLine.b.y-oy).toFixed(4)}" stroke="#00a9b8" stroke-width=".024" stroke-dasharray=".2 .12"/>`;
  g+=`<path d="${bcPtsToPath(shift(m.stabilizer.pts),true)}" fill="none" stroke="${BC.stabilizer}" stroke-width=".04" stroke-linejoin="round"/>`;
  const rows=[["Stabilizer cut envelope",`${bcFmt(bb.w)} W × ${bcFmt(bb.h)} H`],["Offset from fabric cut edge",bcFmt(m.stabilizer.offset)],["Cut quantity",`${m.quantity} · ${m.labels.layout}`],["Fabric finished size",`${bcFmt(m.checks.topW)} top · ${bcFmt(m.checks.botW)} bottom · ${bcFmt(m.checks.height)} H · ${bcFmt(m.checks.depth)} D`],["Construction",`${m.labels.shape} · ${m.labels.topMode}`]];
  bcPrintDoc("Boxed Corner — Stabilizer",g,bb.w+P*2,bb.h+P*2,rows,"Green solid = stabilizer cut line · purple dash-dot = center / place on fold · cyan dashed = bottom fold.");
}

function BcResultBand({m}){const c=m.construction.bottomCorner;return <><div className="bc-resultBand"><div className="bc-resultLine"><div className="bc-resultCell"><div className="rk">Panel Cut Envelope</div><div className="rv">{bcFmt(m.cutBB.w)} W × {bcFmt(m.cutBB.h)} H</div></div><div className="bc-resultCell"><div className="rk">Cut Quantity</div><div className="rv">{m.quantity} · {m.labels.layout}</div></div></div><div className="bc-resultLine"><div className="bc-resultCell"><div className="rk">Corner From Side Edge</div><div className="rv">{bcFmt(c.sideLegCut)}</div></div><div className="bc-resultCell"><div className="rk">Corner From {m.params.layout==="fold"?"Fold":"Bottom Edge"}</div><div className="rv">{bcFmt(c.edgeLegCut)}</div></div></div><div className="bc-resultLine"><div className="bc-resultCell"><div className="rk">Matched After Sewing</div><div className="rv small">{bcFmt(c.sideLegFinished)} side · {bcFmt(c.edgeLegFinished)} bottom/fold</div></div><div className="bc-resultCell"><div className="rk">Construction</div><div className="rv small">{m.labels.shape} · {m.labels.topMode}</div></div></div>{m.stabilizer?.enabled&&m.stabilizer.valid&&<div className="bc-resultLine"><div className="bc-resultCell"><div className="rk">Stabilizer Cut Envelope</div><div className="rv">{bcFmt(m.stabilizer.bb.w)} W × {bcFmt(m.stabilizer.bb.h)} H</div></div><div className="bc-resultCell"><div className="rk">Stabilizer Offset</div><div className="rv">{bcFmt(m.stabilizer.offset)}</div></div></div>}</div><div className="bc-checkGrid">{[["Top",m.checks.topW],["Bottom",m.checks.botW],["Height",m.checks.height],["Depth",m.checks.depth]].map(x=><div className="bc-check" key={x[0]}><div className="k">Finished {x[0]}</div><div className="v">{bcFmt(x[1])} ✓</div></div>)}</div></>}


export default function BoxedCornerPage(){
  const th=BC_THEME;
  const [twW,setTwW]=useState(7),[twF,setTwF]=useState(0);const [bwW,setBwW]=useState(10),[bwF,setBwF]=useState(0);const [hW,setHW]=useState(8),[hF,setHF]=useState(0);const [dW,setDW]=useState(4),[dF,setDF]=useState(0);const [saW,setSaW]=useState(0),[saF,setSaF]=useState(DEFAULT_SA);
  const [layout,setLayout]=useState("two"),[shape,setShape]=useState("rect"),[topMode,setTopMode]=useState("open"),[decMode,setDecMode]=useState(false);
  const [stabEnabled,setStabEnabled]=useState(false),[stabW,setStabW]=useState(0),[stabF,setStabF]=useState(DEFAULT_SA),[stabPrintMode,setStabPrintMode]=useState("overlay");
  const floatRef=useRef(null),dragRef=useRef(null),resizeRef=useRef(null);const [dragging,setDragging]=useState(false),[resizing,setResizing]=useState(false),[floatOpen,setFloatOpen]=useState(true),[canFloat,setCanFloat]=useState(()=>typeof window!=="undefined"?window.innerWidth>=900:false),[dockSide,setDockSide]=useState("right"),[collapsed,setCollapsed]=useState(true);
  const [floatPos,setFloatPos]=useState(()=>({x:typeof window!=="undefined"?Math.max(18,window.innerWidth-358):18,y:86}));const [floatSize,setFloatSize]=useState({w:340,h:355});
  const sa=saW+saF,stabilizerOffset=stabW+stabF;
  const setStabilizerValue=v=>{const n=Math.max(0,+v||0),w=Math.floor(n);setStabW(w);setStabF(n-w);};
  const params={topW:shape==="rect"?bwW+bwF:twW+twF,botW:bwW+bwF,height:hW+hF,depth:dW+dF,sa,layout,shape,topMode,stabilizerEnabled:stabEnabled,stabilizerOffset};
  const m=buildBoxedCornerModel(params),plan=cpTilePlan(m.cutBB.w+.8,m.cutBB.h+.8),stabPlan=m.stabilizer?.valid&&m.stabilizer.bb?cpTilePlan(m.stabilizer.bb.w+.8,m.stabilizer.bb.h+.8):null;
  const overlayRequested=stabEnabled&&stabPrintMode==="overlay",overlayStabilizer=overlayRequested&&m.stabilizer.valid;
  const clampSize=z=>typeof window==="undefined"?z:{w:Math.max(280,Math.min(z.w,Math.min(620,window.innerWidth-20))),h:Math.max(250,Math.min(z.h,Math.min(720,window.innerHeight-20)))};const clampPos=(z,size=floatSize)=>{if(typeof window==="undefined")return z;const q=clampSize(size),p=10;return{x:Math.max(p,Math.min(z.x,window.innerWidth-q.w-p)),y:Math.max(p,Math.min(z.y,window.innerHeight-q.h-p))}};
  const dock=x=>{setDockSide(x);setCollapsed(true);setFloatOpen(true)};const undock=()=>{if(typeof window==="undefined")return;const r=floatRef.current?.getBoundingClientRect(),sz=clampSize({w:r?.width||floatSize.w,h:r?.height||floatSize.h});setFloatSize(sz);setDockSide(null);setCollapsed(false);setFloatPos(clampPos({x:Math.max(12,(window.innerWidth-sz.w)/2),y:Math.max(74,r?.top||86)},sz));};
  const reset=()=>{if(typeof window==="undefined")return;const sz=clampSize({w:340,h:355});setFloatSize(sz);setDockSide(null);setCollapsed(false);setFloatOpen(true);setFloatPos(clampPos({x:window.innerWidth-sz.w-18,y:86},sz));};
  const startDrag=e=>{if((e.button!==undefined&&e.button!==0)||e.target.closest("button")||dockSide)return;const r=floatRef.current?.getBoundingClientRect();if(!r)return;dragRef.current={dx:e.clientX-r.left,dy:e.clientY-r.top,lastX:e.clientX};setDragging(true);e.preventDefault();};const startResize=e=>{const r=floatRef.current?.getBoundingClientRect();if(!r)return;resizeRef.current={x:e.clientX,y:e.clientY,w:r.width,h:r.height,side:dockSide};setResizing(true);e.preventDefault();e.stopPropagation();};
  useEffect(()=>{const f=()=>{setCanFloat(window.innerWidth>=900);setFloatSize(x=>clampSize(x));if(!dockSide)setFloatPos(x=>clampPos(x));};f();window.addEventListener("resize",f);return()=>window.removeEventListener("resize",f)},[dockSide]);
  useEffect(()=>{if(!dragging)return;const move=e=>{const d=dragRef.current;if(!d)return;d.lastX=e.clientX;setFloatPos(clampPos({x:e.clientX-d.dx,y:e.clientY-d.dy}))};const stop=()=>{const d=dragRef.current;if(d?.lastX<=34)dock("left");else if(d?.lastX>=window.innerWidth-34)dock("right");dragRef.current=null;setDragging(false)};window.addEventListener("pointermove",move);window.addEventListener("pointerup",stop,{once:true});return()=>{window.removeEventListener("pointermove",move);window.removeEventListener("pointerup",stop)}},[dragging,floatSize]);
  useEffect(()=>{if(!resizing)return;const move=e=>{const r=resizeRef.current;if(!r)return;const dx=r.side==="right"?r.x-e.clientX:e.clientX-r.x,next=clampSize({w:r.w+dx,h:r.h+e.clientY-r.y});setFloatSize(next);if(!r.side)setFloatPos(x=>clampPos(x,next))};const stop=()=>{resizeRef.current=null;setResizing(false)};window.addEventListener("pointermove",move);window.addEventListener("pointerup",stop,{once:true});return()=>{window.removeEventListener("pointermove",move);window.removeEventListener("pointerup",stop)}},[resizing,dockSide]);
  return <div className="tab-page" data-group="bag-structures"><div className="tab-content-wrap"><div className="tab-intro-card"><div className="tab-intro-card-thumb"/><div className="tab-intro-card-text"><div className="tab-intro-card-title">Boxed Bottom</div><div className="tab-intro-card-desc">Work backward from finished width, height, and depth to get exact cut dimensions for boxed corner panels. Supports rectangles and trapezoids, open and enclosed tops, folded or separate layouts, and optional stabilizer overlays.</div></div></div><div><div className="bc-topbar"><div className="bc-hint" style={{margin:0}}>The diagram, dimension checks, and full-size print pattern all use the same geometry model.</div>{!isMetric()&&<label className="bc-decToggle"><input type="checkbox" checked={decMode} onChange={e=>setDecMode(e.target.checked)}/>Decimal input</label>}</div>
    <div className="bc-card"><div className="bc-controlSection"><h2>Finished Dimensions</h2><div className="bc-row"><FracInput variant="bc" label="Top width" ghost={shape==="rect"} decMode={decMode} whole={shape==="rect"?bwW:twW} frac={shape==="rect"?bwF:twF} onWhole={setTwW} onFrac={setTwF}/><FracInput variant="bc" label="Bottom width" decMode={decMode} whole={bwW} frac={bwF} onWhole={setBwW} onFrac={setBwF}/><FracInput variant="bc" label="Height" decMode={decMode} whole={hW} frac={hF} onWhole={setHW} onFrac={setHF}/><FracInput variant="bc" label="Depth" decMode={decMode} whole={dW} frac={dF} onWhole={setDW} onFrac={setDF}/><FracInput variant="bc" label="Seam allowance" decMode={decMode} whole={saW} frac={saF} onWhole={setSaW} onFrac={setSaF}/></div><p className="bc-hint">For a rectangle, top width follows bottom width. A trapezoid may use different top and bottom widths.</p></div><div className="bc-lowerControls"><div className="bc-controlSection"><h2>Panel Layout</h2><BcSeg value={layout} set={setLayout} options={[{id:"two",label:"2 Separate Panels"},{id:"fold",label:"1 Mirrored Fold"}]}/><p className="bc-hint">The folded piece has no bottom seam allowance. Its side-edge corner leg still includes seam allowance so both boxed edges match after the side seam is sewn.</p></div><div className="bc-controlSection"><h2>Shape & Top</h2><BcSeg value={shape} set={setShape} options={[{id:"rect",label:"Rectangle"},{id:"trap",label:"Trapezoid"}]}/><div style={{height:6}}/><BcSeg value={topMode} set={setTopMode} options={[{id:"open",label:"Open Top"},{id:"enclosed",label:"Top Boxed"}]}/><p className="bc-hint">Every trapezoid box-cut leg leaves its own source edge at 90°; the two legs meet at the finished face corner.</p></div></div></div>
    <div className="bc-card"><div className="bc-controlSection"><h2>Stabilizer</h2><BcSeg value={stabEnabled?"add":"none"} set={v=>setStabEnabled(v==="add")} options={[{id:"none",label:"No Stabilizer"},{id:"add",label:"Add Stabilizer"}]}/>{stabEnabled&&<><div className="bc-stabGrid"><FracInput variant="bc" label="Offset from fabric cut edge" decMode={decMode} whole={stabW} frac={stabF} onWhole={setStabW} onFrac={setStabF}/><button className="bc-matchSa" onClick={()=>setStabilizerValue(sa)}>Match Seam Allowance</button><div className="bc-stabPrint"><label>Print stabilizer</label><BcSeg value={stabPrintMode} set={setStabPrintMode} options={[{id:"overlay",label:"On Main Pattern"},{id:"separate",label:"Separately"}]}/></div></div><p className="bc-hint">The stabilizer is one continuous inset of the fabric outline. Matching the seam allowance keeps it out of the stitched seams; on sewn edges, the green stabilizer line will intentionally coincide with the grey stitch line. Choose a larger offset when you want more clearance.</p></>}</div></div>
    {m.notes.length>0&&<div className="bc-warn">Geometry note:<ul>{m.notes.map((x,i)=><li key={i}>{x}</li>)}</ul></div>}
    <TrustBadge tone="bc" valid={m.valid}
      okMessage="✓ Finished dimensions verified: top, bottom, height, and depth reconstruct exactly from the cut geometry."
      lockLabel="Pattern output locked" errors={m.errors}/>
    {stabEnabled&&<TrustBadge tone="bc" valid={m.stabilizer.valid}
      okMessage={`✓ Stabilizer outline verified ${bcFmt(m.stabilizer.offset)} inside every fabric cut edge.`}
      lockLabel="Stabilizer output locked" errors={m.stabilizer.errors}/>}
    <div className="bc-card bc-diagramCard"><svg viewBox="0 0 760 520" style={{width:"100%",height:"auto",display:"block"}} role="img" aria-label="Live boxed corner panel diagram" dangerouslySetInnerHTML={{__html:bcPanelDiagramSVG(m)}}/><p className="bc-diagramLegend">Solid pumpkin = fabric cut &nbsp; Grey dashed = assembly stitch lines &nbsp; Purple dash-dot = center / place on fold &nbsp; Cyan dashed = bottom fold {stabEnabled&&m.stabilizer.valid&&<>&nbsp; Green dash-dot = stabilizer cut</>}</p></div>{m.valid&&<BcResultBand m={m}/>} 
    {canFloat&&floatOpen&&dockSide&&collapsed&&<button className={"bc-dockTab "+dockSide} style={{top:Math.max(86,Math.min(floatPos.y,typeof window!=="undefined"?window.innerHeight-210:120))}} onClick={undock}><span className="bc-liveDot" style={{background:m.valid?"#2f9a62":"#c23b47"}}/>Live Pattern Feed</button>}
    {canFloat&&floatOpen&&!(dockSide&&collapsed)&&<div ref={floatRef} className={"bc-floatDock"+(dragging?" dragging":"")+(resizing?" resizing":"")+(dockSide?" docked-"+dockSide:"")} style={dockSide?{[dockSide]:0,top:Math.max(72,Math.min(floatPos.y,typeof window!=="undefined"?window.innerHeight-Math.min(floatSize.h,window.innerHeight-82)-10:86)),width:floatSize.w,height:typeof window!=="undefined"?Math.min(floatSize.h,window.innerHeight-82):floatSize.h}:{left:floatPos.x,top:floatPos.y,width:floatSize.w,height:floatSize.h}}><div className="bc-floatHead" onPointerDown={startDrag}><div className="bc-missionBrand"><span className="bc-liveDot" style={{background:m.valid?"#2f9a62":"#c23b47"}}/><div><div className="bc-missionTitle">MoonShot Mission Control</div><div className="bc-missionFeed">Live Boxed-Corner Feed</div></div></div><button className="bc-floatClose" onPointerDown={e=>e.stopPropagation()} onClick={()=>{setDockSide(dockSide||"right");setCollapsed(true)}}>×</button></div><div className="bc-floatNav"><button onClick={()=>dock("left")}>← Dock Left</button><button onClick={reset}>ReCenter</button><button onClick={()=>dock("right")}>Dock Right →</button></div><div className="bc-floatBody"><svg viewBox="0 0 760 520" style={{width:"100%",height:"auto",display:"block"}} dangerouslySetInnerHTML={{__html:bcPanelDiagramSVG(m)}}/><div className="bc-floatMeta">{bcFmt(m.cutBB.w)} W × {bcFmt(m.cutBB.h)} H cut · {bcFmt(params.depth)} finished depth · {m.labels.layout}</div></div><div className={"bc-resizeHandle "+(dockSide==="right"?"left":"right")} onPointerDown={startResize}/></div>}
    <div className="bc-card" style={{marginTop:8}}><h2>Print Pattern</h2><div className="bc-printGrid"><div className="bc-printCard"><div className="pt">Main Panel</div><div className="pm">Actual-size fabric cut outline, assembly stitch lines only, center place-on-fold line, bottom fold where used, perpendicular-corner marks, registration crosses, and test squares.{overlayStabilizer?" The stabilizer cut line is overlaid in green.":""}</div><PrintButton tone="bc" label="Print Main Panel" meta={cpTileLabel(plan)} disabled={!m.valid||(overlayRequested&&!m.stabilizer.valid)} onClick={()=>bcPrintPanel(m,overlayStabilizer)}/></div>{stabEnabled&&stabPrintMode==="separate"&&<div className="bc-printCard"><div className="pt">Stabilizer</div><div className="pm">A separate actual-size pattern inset {bcFmt(stabilizerOffset)} from the fabric cut edge, with its own center place-on-fold line and bottom fold when applicable.</div><PrintButton tone="bc" label="Print Stabilizer" meta={stabPlan?cpTileLabel(stabPlan):"Adjust stabilizer offset"} disabled={!m.valid||!m.stabilizer.valid||!stabPlan} onClick={()=>bcPrintStabilizer(m)}/></div>}</div></div>
  </div></div></div>;
}
